### PR TITLE
"LOCKING" scancodes was disabled in original header

### PR DESCRIPTION
**Pull request by vuvk**
See SDL_scancode.h (lines 241-244):
```
/* not sure whether there's a reason to enable these */
/*     SDL_SCANCODE_LOCKINGCAPSLOCK = 130,  */
/*     SDL_SCANCODE_LOCKINGNUMLOCK = 131, */
/*     SDL_SCANCODE_LOCKINGSCROLLLOCK = 132, */
```

### CODE REVIEW

**Comment by desiderantes** [comment]
I'd just remove them, apparently they were removed in the first version of SDL2

**Comment by vuvk** [comment]
Why not? And you can change int init to bool init in SDL2_image

**Comment by desiderantes** [comment]
I removed them, thanks to bringing this to my attention. I will close this PR and apply the SDL_Image change you suggested

**Comment by vuvk** [comment]
Thanks

**Comment by desiderantes** [comment]
On a second look, SDL_Image_Init can't return a boolean, on success it returns the mask of the flags that succeeded.

**Comment by vuvk** [comment]
Ah, yes, sorry :) I forgot

**Pull request closed without merging**
